addons:
  chrome: stable

language: node_js

node_js:
  - 'node'

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - yarn install

# Init GUI
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  #- apt-get install graphicsmagick # for e2e screenshots

script:
  - echo "skipping tests"

cache:
  directories:
    - ./node_modules

deploy:
  provider: script
  script: "npm run deploy"
  skip_cleanup: true
  on:
    branch: master



notifications:
  email: false
